before_script:
  - chmod +x ./gradlew

stages:
  - build

build_app:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/apk/debug/output.json